[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ptf_dex = "2hktsrLk3f6EN7vHR3cYgoTHXJE9Hw4HsU5MRgXtAPZ8"
ptf_factory = "GQhkApwhBSy65JGFNpKBfFSNkhxjuJG5g8oY2DQhDN5P"
ptf_pool = "3aBs2hhifpWZnECCRACnBAHYokMKfGcMm4PxiF8E8zvE"
ptf_vault = "Muko1fue2j1At1U6v2xJ7cuwas5uSUjZHVGppbpT8yq"
ptf_verifier_groth16 = "9X9pUY6B828TVGwtwEqmmqkkCSUTt3zLr3dvKJzfWgin"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/factory", "programs/vault", "programs/pool", "programs/verifier-groth16", "programs/dex"]

[hooks]
