[workspace]
members = [
  "programs/factory",
  "programs/vault",
  "programs/pool",
  "programs/verifier-groth16"
]

[programs.localnet]
ptf_factory = "YNZGqPEsKkMcUopmXThpigDdxfCYPE6jS1QtsXfRzjV"
ptf_vault = "ABUQvsF8kdY9HCFrVEomafg9ABbq4zVQuxLfevpwGnvb"
ptf_pool = "GBfBiuyXm5YZjnCPkZNjakht41rxEkMRxawQcocowwdi"
ptf_verifier_groth16 = "3aCv39mCRFH9BGJskfXqwQoWzW1ULq2yXEbEwGgKtLgg"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

