[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ptf_dex = "5Dvt8enX3PgC5hJmzcpB7iuZX6LcYYLP12WXVv7Uef2G"
ptf_factory = "6uruFJACS8n2H28vWA39XqnPwRinL3P1DPLipySZfAuM"
ptf_pool = "F8bEMyP6Yt3SMGVT9jKL6m13Sn6mc1Z5AeuuJPNCR8to"
ptf_vault = "Cp154M1oxXYJDbrgg9f57ytuthW8X8WNe73NQ7kQQr4Q"
ptf_verifier_groth16 = "geepCeZMrQu1Fh8mXYTxUcZhkw858R2joYXwqRQVS9S"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/factory", "programs/vault", "programs/pool", "programs/verifier-groth16", "programs/dex"]

[hooks]
