[package]
name = "ptf-dex"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "ptf_dex"

[dependencies]
anchor-lang = { workspace = true, features = ["init-if-needed"] }
anchor-spl = { workspace = true }
ptf-common = { path = "../common" }
ptf-pool = { path = "../pool", features = ["no-entrypoint", "cpi"] }
ptf-factory = { path = "../factory", features = ["no-entrypoint", "cpi"] }
ptf-vault = { path = "../vault", features = ["no-entrypoint", "cpi"] }
ptf-verifier-groth16 = { path = "../verifier-groth16", features = ["no-entrypoint", "cpi"] }
thiserror = { workspace = true }
solana-program = { workspace = true }
spl-associated-token-account-client = "2.0.0"

[features]
default = []
no-entrypoint = []
cpi = ["no-entrypoint"]
no-idl = []
idl-build = ["no-entrypoint", "anchor-spl/idl-build", "anchor-lang/idl-build"]
anchor-debug = []
no-log-ix-name = []
custom-heap = []
custom-panic = []
solana = []
integration-tests = []

